// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Comment struct {
	ID       string     `json:"id"`
	Content  string     `json:"content"`
	PostID   string     `json:"postID"`
	ParentID *string    `json:"parentID,omitempty"`
	Replies  []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID       string     `json:"id"`
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	IsLocked bool       `json:"isLocked"`
	Comments []*Comment `json:"comments"`
}

type Query struct {
}
